name: CI

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ advanced ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
#2
env:
  REGISTRY: "izabayo7"
  IMAGE_NAME: "kurious"

#3
jobs:
  build_image:
    runs-on: [self-hosted, linux, x64, docker]
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
        
      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .

  deploy:
    runs-on: [self-hosted, linux, x64, docker]
    needs: build_image
    
    steps:
      # - name: Stop running container
      #   run: docker stop $(echo $IMAGE_NAME)
      # - name: Remove old container
      #   run: docker rm $(echo $IMAGE_NAME)
      - name: Run a new container from a new image
        run: docker run -d \
            --restart always \
            --name $(echo $IMAGE_NAME) \
            $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
