# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production CI

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: [self-hosted, linux, x64, prod]
    env:
      HOME: /root
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build --if-present
      - run: rm -rf /var/www/learn.kurious.rw/builds/prod/dist
      - run: mv /var/www/learn.kurious.rw/actions-runner/deploy/Kurious-Frontend/Kurious-Frontend/dist /var/www/learn.kurious.rw/builds/prod/